---

- name: load OS specific variables
  include_vars:
    file: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- debug: var=iptables
  tags:
    - never
    - debug

- debug: var=ip6tables
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version in ["6","7"]

- name: iptables package is present
  package:
    name: "{{ iptables.package }}"
    state: present
# iptables-restore reads from stdin
# input redirection is not present for validate
#
- name: iptables-restore-wrapper is present
  loop:
    - iptables-restore-test
    - ip6tables-restore-test
  copy:
    src: "{{ item }}"
    dest: /usr/local/sbin/
    mode: 00750

- name: iptables is configured
  when: iptables_script is defined
  template:
    src: "{{ playbook_dir + '/' + iptables_script }}"
    dest: /etc/sysconfig/iptables
    backup: true
    owner: root
    mode: 00600
    validate: "/usr/local/sbin/iptables-restore-test %s"
  notify:
    - reload iptables

- name: iptables is configured
  when: not iptables_script is defined
  template:
    src: iptables
    dest: /etc/sysconfig/iptables
    backup: true
    owner: root
    mode: 00600
    validate: "/usr/local/sbin/iptables-restore-test %s"
  notify:
    - reload iptables

- name: ip6tables is configured
  when: ip6tables_script is defined
  template:
    src: "{{ ip6tables.script }}"
    dest: /etc/sysconfig/ip6tables
    backup: true
    mode: 00600
    validate: "/usr/local/sbin/ip6tables-restore-test %s"
  notify:
    - reload ip6tables

- name: ip6tables is configured
  when: not ip6tables_script is defined
  template:
    src: ip6tables
    dest: /etc/sysconfig/ip6tables
    backup: true
    mode: 00600
    validate: "/usr/local/sbin/ip6tables-restore-test %s"
  notify:
    - reload ip6tables

- name: iptables service is started
  loop:
    - iptables
    - ip6tables
  service:
    name: "{{ item }}"
    state: started
    enabled: true
